### ISSUE TITLE
Bugs in code

### ISSUE THREAD

**Issue by Gammamad** [Yu3Ga0SioMGames/Structures#1]
Косяк 1
https://github.com/Yu3Ga0SioMGames/Structures/blob/f88a8df88eb3d8ad89aca1f333ce95597121d0e4/stack.c#L44
https://github.com/Yu3Ga0SioMGames/Structures/blob/f88a8df88eb3d8ad89aca1f333ce95597121d0e4/stack.c#L55
https://github.com/Yu3Ga0SioMGames/Structures/blob/f88a8df88eb3d8ad89aca1f333ce95597121d0e4/stack.c#L73
https://github.com/Yu3Ga0SioMGames/Structures/blob/f88a8df88eb3d8ad89aca1f333ce95597121d0e4/stack.c#L89
https://github.com/Yu3Ga0SioMGames/Structures/blob/f88a8df88eb3d8ad89aca1f333ce95597121d0e4/stack.c#L102

Ошибки:
1) Печать пустого стэка это не ошибка, просто пустая строка пусть выводится

2) Если расширение памяти свалится с ошибкой функция всё равно продолжит код вставки...
https://github.com/Yu3Ga0SioMGames/Structures/blob/f88a8df88eb3d8ad89aca1f333ce95597121d0e4/stack.c#L78

**Comment by Yu3Ga0SioMGames** [comment]
Исправленно!
